# Generated by Django 4.0.3 on 2022-12-19 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'practice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'route',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('statistics_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('burned_calories', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name="user's identification")),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('password', models.CharField(max_length=20)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weigth', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('avatar', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=45)),
                ('second_name', models.CharField(db_column='second name', max_length=45)),
                ('nick', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=3, null=True)),
                ('friend', models.ManyToManyField(blank=True, to='MSBWebsite_App.user')),
                ('practice', models.ManyToManyField(to='MSBWebsite_App.practice')),
                ('route', models.ManyToManyField(to='MSBWebsite_App.route')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ranking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('limit_of_participants', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('ranking', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='MSBWebsite_App.ranking')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MSBWebsite_App.route')),
            ],
            options={
                'db_table': 'race',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='practice',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MSBWebsite_App.route'),
        ),
        migrations.AddField(
            model_name='practice',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='MSBWebsite_App.statistics'),
        ),
    ]
